# Generated by Django 5.2.17 on 2026-08-11 01:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0002_add_service_catalog_constraints'),
        ('workspaces', '0002_alter_membership_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('issued_on', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted')], default='DRAFT', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='clients.client')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(choices=[('HOUR', 'Hour'), ('PROJECT', 'Project'), ('DELIVERABLE', 'Deliverable')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='proposals.proposal')),
                ('source_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_line_items', to='services.service')),
            ],
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('issued_on'))), name='proposal_valid_until_on_or_after_issued'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('converted_at__isnull', True), ('expired_at__isnull', True), ('rejected_at__isnull', True), ('sent_at__isnull', True), ('status', 'DRAFT')), models.Q(('accepted_at__isnull', True), ('converted_at__isnull', True), ('expired_at__isnull', True), ('rejected_at__isnull', True), ('sent_at__isnull', False), ('status', 'SENT')), models.Q(('accepted_at__isnull', False), ('converted_at__isnull', True), ('expired_at__isnull', True), ('rejected_at__isnull', True), ('sent_at__isnull', False), ('status', 'ACCEPTED')), models.Q(('accepted_at__isnull', True), ('converted_at__isnull', True), ('expired_at__isnull', True), ('rejected_at__isnull', False), ('sent_at__isnull', False), ('status', 'REJECTED')), models.Q(('accepted_at__isnull', True), ('converted_at__isnull', True), ('expired_at__isnull', False), ('rejected_at__isnull', True), ('sent_at__isnull', False), ('status', 'EXPIRED')), models.Q(('accepted_at__isnull', False), ('converted_at__isnull', False), ('expired_at__isnull', True), ('rejected_at__isnull', True), ('sent_at__isnull', False), ('status', 'CONVERTED')), _connector='OR'), name='proposal_status_timestamps_consistent'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.CheckConstraint(condition=models.Q(('archived_at__isnull', True), ('status__in', ['REJECTED', 'EXPIRED', 'CONVERTED']), _connector='OR'), name='proposal_archive_requires_terminal_status'),
        ),
        migrations.AddConstraint(
            model_name='proposallineitem',
            constraint=models.UniqueConstraint(fields=('proposal', 'position'), name='unique_proposal_line_position'),
        ),
        migrations.AddConstraint(
            model_name='proposallineitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0.00'))), name='proposal_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='proposallineitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_rate__gte', Decimal('0.00'))), name='proposal_line_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='proposallineitem',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='proposal_line_currency_usd_only'),
        ),
        migrations.AddConstraint(
            model_name='proposallineitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_of_measure__in', ['HOUR', 'PROJECT', 'DELIVERABLE'])), name='proposal_line_unit_allowed'),
        ),
    ]
