# Generated by Django 5.2.17 on 2026-08-11 04:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('proposals', '0002_enforce_proposal_immutability'),
        ('workspaces', '0002_alter_membership_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='proposals.proposal')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='workspaces.workspace')),
            ],
            options={
                'base_manager_name': 'objects',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('cancelled_at__isnull', True), ('completed_at__isnull', True), ('status', 'ACTIVE')), models.Q(('cancelled_at__isnull', True), ('completed_at__isnull', False), ('status', 'COMPLETED')), models.Q(('cancelled_at__isnull', False), ('completed_at__isnull', True), ('status', 'CANCELLED')), _connector='OR'), name='project_status_timestamps_archive_consistent')],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER project_source_matches_proposal_on_insert
                BEFORE INSERT ON projects_project
                FOR EACH ROW
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM proposals_proposal
                        WHERE id = NEW.proposal_id
                          AND workspace_id = NEW.workspace_id
                          AND client_id = NEW.client_id
                    ) THEN
                        SIGNAL SQLSTATE '45000'
                            SET MESSAGE_TEXT = 'Project source must match proposal workspace and client.';
                    END IF;
                END
            """,
            reverse_sql="DROP TRIGGER IF EXISTS project_source_matches_proposal_on_insert",
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER project_source_immutable_on_update
                BEFORE UPDATE ON projects_project
                FOR EACH ROW
                BEGIN
                    IF NOT (NEW.workspace_id <=> OLD.workspace_id)
                       OR NOT (NEW.client_id <=> OLD.client_id)
                       OR NOT (NEW.proposal_id <=> OLD.proposal_id) THEN
                        SIGNAL SQLSTATE '45000'
                            SET MESSAGE_TEXT = 'Project source is immutable.';
                    END IF;
                    IF NOT EXISTS (
                        SELECT 1 FROM proposals_proposal
                        WHERE id = NEW.proposal_id
                          AND workspace_id = NEW.workspace_id
                          AND client_id = NEW.client_id
                    ) THEN
                        SIGNAL SQLSTATE '45000'
                            SET MESSAGE_TEXT = 'Project source must match proposal workspace and client.';
                    END IF;
                END
            """,
            reverse_sql="DROP TRIGGER IF EXISTS project_source_immutable_on_update",
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER project_no_delete
                BEFORE DELETE ON projects_project
                FOR EACH ROW
                BEGIN
                    SIGNAL SQLSTATE '45000'
                        SET MESSAGE_TEXT = 'Projects cannot be deleted.';
                END
            """,
            reverse_sql="DROP TRIGGER IF EXISTS project_no_delete",
        ),
    ]
