# Generated by Django 5.2.17 on 2026-08-10 19:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_alter_membership_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_normalized', models.CharField(editable=False, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(choices=[('HOUR', 'Hour'), ('PROJECT', 'Project'), ('DELIVERABLE', 'Deliverable')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='workspaces.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'name_normalized'), name='unique_service_name_per_workspace'), models.CheckConstraint(condition=models.Q(('rate__gte', Decimal('0.00'))), name='service_rate_nonnegative'), models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('status', 'ACTIVE')), models.Q(('archived_at__isnull', False), ('status', 'ARCHIVED')), _connector='OR'), name='service_status_archived_at_consistent')],
            },
        ),
    ]
