# Generated by Django 5.2.17 on 2026-08-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('workspaces', '0002_alter_membership_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='service_currency_usd_only'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('unit_of_measure__in', ['HOUR', 'PROJECT', 'DELIVERABLE'])), name='service_unit_of_measure_allowed'),
        ),
    ]
