# Generated by Django 5.2.17 on 2026-08-11 06:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_alter_membership_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('legal_name', models.CharField(max_length=255)),
                ('tax_identifier', models.CharField(max_length=100)),
                ('tax_regime', models.CharField(max_length=100)),
                ('applies_vat', models.BooleanField()),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('withholding_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_configurations', to='workspaces.workspace')),
            ],
            options={
                'base_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'version'), name='fiscal_configuration_workspace_version_unique'), models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='fiscal_configuration_version_positive'), models.CheckConstraint(condition=models.Q(('vat_rate__gte', Decimal('0.00')), ('vat_rate__lte', Decimal('100.00')), ('withholding_rate__gte', Decimal('0.00')), ('withholding_rate__lte', Decimal('100.00'))), name='fiscal_configuration_rates_in_range'), models.CheckConstraint(condition=models.Q(models.Q(('applies_vat', False), ('vat_rate', Decimal('0.00'))), models.Q(('applies_vat', True), ('vat_rate__gt', Decimal('0.00'))), _connector='OR'), name='fiscal_configuration_vat_consistent')],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER fiscal_configuration_validate_insert
                BEFORE INSERT ON fiscal_fiscalconfiguration
                FOR EACH ROW
                BEGIN
                    IF NEW.version <= 0
                       OR NEW.vat_rate < 0 OR NEW.vat_rate > 100
                       OR NEW.withholding_rate < 0 OR NEW.withholding_rate > 100
                       OR (NEW.applies_vat = 0 AND NEW.vat_rate <> 0)
                       OR (NEW.applies_vat = 1 AND NEW.vat_rate <= 0) THEN
                        SIGNAL SQLSTATE '45000'
                            SET MESSAGE_TEXT = 'Fiscal configuration values are invalid.';
                    END IF;
                END
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER fiscal_configuration_immutable_update
                BEFORE UPDATE ON fiscal_fiscalconfiguration
                FOR EACH ROW
                BEGIN
                    SIGNAL SQLSTATE '45000'
                        SET MESSAGE_TEXT = 'Fiscal configurations are immutable.';
                END
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER fiscal_configuration_immutable_delete
                BEFORE DELETE ON fiscal_fiscalconfiguration
                FOR EACH ROW
                BEGIN
                    SIGNAL SQLSTATE '45000'
                        SET MESSAGE_TEXT = 'Fiscal configurations are immutable.';
                END
            """,
            reverse_sql=None,
        ),
    ]
