# Generated by Django 5.2.17 on 2026-08-10 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_alter_membership_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('client_type', models.CharField(choices=[('COMPANY', 'Company'), ('INDIVIDUAL', 'Individual')], max_length=20)),
                ('tax_identifier', models.CharField(max_length=64)),
                ('tax_identifier_normalized', models.CharField(editable=False, max_length=64)),
                ('primary_contact_name', models.CharField(max_length=255)),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='workspaces.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'tax_identifier_normalized'), name='unique_client_tax_identifier_per_workspace'), models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('status', 'ACTIVE')), models.Q(('archived_at__isnull', False), ('status', 'ARCHIVED')), _connector='OR'), name='client_status_archived_at_consistent')],
            },
        ),
    ]
