# Generated by Django 5.2.17 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="civil_status",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="telephone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
