# Generated by Django 5.2.17 on 2026-08-11 18:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('fiscal', '0002_enforce_sequential_fiscal_versions'),
        ('projects', '0002_require_accepted_proposal_for_project'),
        ('workspaces', '0002_alter_membership_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('VOID', 'Void')], default='DRAFT', max_length=10)),
                ('fiscal_version', models.PositiveIntegerField(blank=True, null=True)),
                ('fiscal_legal_name', models.CharField(blank=True, max_length=255)),
                ('fiscal_tax_identifier', models.CharField(blank=True, max_length=100)),
                ('fiscal_tax_regime', models.CharField(blank=True, max_length=100)),
                ('fiscal_applies_vat', models.BooleanField(blank=True, null=True)),
                ('fiscal_vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fiscal_withholding_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client')),
                ('fiscal_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fiscal.fiscalconfiguration')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='workspaces.workspace')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(choices=[('HOUR', 'Hour'), ('PROJECT', 'Project'), ('DELIVERABLE', 'Deliverable')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('withholding_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='invoices.invoice')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_sequence', to='workspaces.workspace')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('workspace', 'number'), name='invoice_workspace_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('fiscal_vat_rate__isnull', True), models.Q(('fiscal_vat_rate__gte', Decimal('0.00')), ('fiscal_vat_rate__lte', Decimal('100.00'))), _connector='OR'), name='invoice_fiscal_vat_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('fiscal_withholding_rate__isnull', True), models.Q(('fiscal_withholding_rate__gte', Decimal('0.00')), ('fiscal_withholding_rate__lte', Decimal('100.00'))), _connector='OR'), name='invoice_fiscal_withholding_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'position'), name='invoice_line_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0.00'))), name='invoice_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_rate__gte', Decimal('0.00'))), name='invoice_line_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='invoice_line_currency_usd'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('vat_rate__gte', Decimal('0.00')), ('vat_rate__lte', Decimal('100.00'))), name='invoice_line_vat_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('withholding_rate__gte', Decimal('0.00')), ('withholding_rate__lte', Decimal('100.00'))), name='invoice_line_withholding_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='invoicesequence',
            constraint=models.CheckConstraint(condition=models.Q(('next_number__gt', 0)), name='invoice_sequence_next_positive'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER invoice_validate_insert
                BEFORE INSERT ON invoices_invoice
                FOR EACH ROW
                BEGIN
                    DECLARE project_workspace BIGINT;
                    DECLARE project_client BIGINT;
                    DECLARE fiscal_workspace BIGINT;
                    DECLARE fiscal_version INT;
                    DECLARE fiscal_name VARCHAR(255);
                    DECLARE fiscal_identifier VARCHAR(100);
                    DECLARE fiscal_regime VARCHAR(100);
                    DECLARE fiscal_vat BOOLEAN;
                    DECLARE fiscal_vat_rate DECIMAL(5,2);
                    DECLARE fiscal_withholding DECIMAL(5,2);
                    SELECT workspace_id, client_id INTO project_workspace, project_client FROM projects_project WHERE id = NEW.project_id;
                    IF project_workspace IS NULL OR NEW.workspace_id <> project_workspace OR NEW.client_id <> project_client THEN
                        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invoice source must match its project.';
                    END IF;
                    IF NEW.status = 'DRAFT' AND (NEW.number IS NOT NULL OR NEW.fiscal_configuration_id IS NOT NULL OR NEW.fiscal_version IS NOT NULL OR NEW.fiscal_legal_name <> '' OR NEW.fiscal_tax_identifier <> '' OR NEW.fiscal_tax_regime <> '' OR NEW.fiscal_applies_vat IS NOT NULL OR NEW.fiscal_vat_rate IS NOT NULL OR NEW.fiscal_withholding_rate IS NOT NULL OR NEW.issued_at IS NOT NULL OR NEW.voided_at IS NOT NULL OR NEW.void_reason <> '') THEN
                        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Draft invoices cannot contain issued data.';
                    END IF;
                    IF NEW.status <> 'DRAFT' THEN
                        SELECT workspace_id, version, legal_name, tax_identifier, tax_regime, applies_vat, vat_rate, withholding_rate INTO fiscal_workspace, fiscal_version, fiscal_name, fiscal_identifier, fiscal_regime, fiscal_vat, fiscal_vat_rate, fiscal_withholding FROM fiscal_fiscalconfiguration WHERE id = NEW.fiscal_configuration_id;
                        IF NEW.number IS NULL OR NEW.number NOT REGEXP '^INV-[0-9]{6}$' OR NEW.issued_at IS NULL OR fiscal_workspace <> NEW.workspace_id OR NOT (NEW.fiscal_version <=> fiscal_version) OR NOT (NEW.fiscal_legal_name <=> fiscal_name) OR NOT (NEW.fiscal_tax_identifier <=> fiscal_identifier) OR NOT (NEW.fiscal_tax_regime <=> fiscal_regime) OR NOT (NEW.fiscal_applies_vat <=> fiscal_vat) OR NOT (NEW.fiscal_vat_rate <=> fiscal_vat_rate) OR NOT (NEW.fiscal_withholding_rate <=> fiscal_withholding) THEN
                            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Issued invoice fiscal snapshot is invalid.';
                        END IF;
                    END IF;
                    IF NEW.status = 'VOID' AND (NEW.voided_at IS NULL OR NEW.void_reason = '') THEN
                        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Void invoices require a reason.';
                    END IF;
                END
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER invoice_validate_update
                BEFORE UPDATE ON invoices_invoice
                FOR EACH ROW
                BEGIN
                    IF NEW.workspace_id <> OLD.workspace_id OR NEW.client_id <> OLD.client_id OR NEW.project_id <> OLD.project_id THEN
                        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invoice origin is immutable.';
                    END IF;
                    IF OLD.status = 'VOID' OR (OLD.status = 'ISSUED' AND NEW.status <> 'VOID') OR (OLD.status = 'DRAFT' AND NEW.status NOT IN ('DRAFT', 'ISSUED')) THEN
                        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invoice transition is invalid.';
                    END IF;
                    IF OLD.status <> 'DRAFT' AND (NOT (NEW.number <=> OLD.number) OR NOT (NEW.fiscal_configuration_id <=> OLD.fiscal_configuration_id) OR NOT (NEW.fiscal_version <=> OLD.fiscal_version) OR NOT (NEW.fiscal_legal_name <=> OLD.fiscal_legal_name) OR NOT (NEW.fiscal_tax_identifier <=> OLD.fiscal_tax_identifier) OR NOT (NEW.fiscal_tax_regime <=> OLD.fiscal_tax_regime) OR NOT (NEW.fiscal_applies_vat <=> OLD.fiscal_applies_vat) OR NOT (NEW.fiscal_vat_rate <=> OLD.fiscal_vat_rate) OR NOT (NEW.fiscal_withholding_rate <=> OLD.fiscal_withholding_rate) OR NOT (NEW.issued_at <=> OLD.issued_at)) THEN
                        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Issued invoice data is immutable.';
                    END IF;
                    IF NEW.status = 'DRAFT' AND (NEW.number IS NOT NULL OR NEW.fiscal_configuration_id IS NOT NULL OR NEW.fiscal_version IS NOT NULL OR NEW.fiscal_legal_name <> '' OR NEW.fiscal_tax_identifier <> '' OR NEW.fiscal_tax_regime <> '' OR NEW.fiscal_applies_vat IS NOT NULL OR NEW.fiscal_vat_rate IS NOT NULL OR NEW.fiscal_withholding_rate IS NOT NULL OR NEW.issued_at IS NOT NULL) THEN
                        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Draft invoices cannot contain issued data.';
                    END IF;
                    IF NEW.status = 'VOID' AND (NEW.voided_at IS NULL OR NEW.void_reason = '') THEN
                        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Void invoices require a reason.';
                    END IF;
                END
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(sql="""CREATE TRIGGER invoice_no_delete BEFORE DELETE ON invoices_invoice FOR EACH ROW BEGIN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invoices cannot be deleted.'; END""", reverse_sql=None),
        migrations.RunSQL(sql="""CREATE TRIGGER invoice_sequence_validate_insert BEFORE INSERT ON invoices_invoicesequence FOR EACH ROW BEGIN IF NEW.next_number <= 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invoice sequence must be positive.'; END IF; END""", reverse_sql=None),
        migrations.RunSQL(sql="""CREATE TRIGGER invoice_sequence_validate_update BEFORE UPDATE ON invoices_invoicesequence FOR EACH ROW BEGIN IF NEW.workspace_id <> OLD.workspace_id OR NEW.next_number <> OLD.next_number + 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invoice sequence must advance by one.'; END IF; END""", reverse_sql=None),
        migrations.RunSQL(sql="""CREATE TRIGGER invoice_sequence_no_delete BEFORE DELETE ON invoices_invoicesequence FOR EACH ROW BEGIN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invoice sequences cannot be deleted.'; END""", reverse_sql=None),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER invoice_line_validate_insert
                BEFORE INSERT ON invoices_invoicelineitem
                FOR EACH ROW
                BEGIN
                    DECLARE source_count INT;
                    SELECT COUNT(*) INTO source_count
                    FROM proposals_proposallineitem source
                    INNER JOIN projects_project project ON project.proposal_id = source.proposal_id
                    INNER JOIN invoices_invoice invoice ON invoice.project_id = project.id
                    WHERE invoice.id = NEW.invoice_id AND invoice.status = 'ISSUED' AND source.position = NEW.position
                      AND source.service_name = NEW.service_name AND source.description <=> NEW.description
                      AND source.unit_of_measure = NEW.unit_of_measure AND source.quantity = NEW.quantity
                      AND source.unit_rate = NEW.unit_rate AND source.currency = NEW.currency;
                    IF source_count <> 1 OR NEW.currency <> 'USD' OR NEW.vat_rate < 0 OR NEW.vat_rate > 100 OR NEW.withholding_rate < 0 OR NEW.withholding_rate > 100 THEN
                        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invoice line snapshot is invalid.';
                    END IF;
                END
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(sql="""CREATE TRIGGER invoice_line_no_update BEFORE UPDATE ON invoices_invoicelineitem FOR EACH ROW BEGIN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invoice lines are immutable.'; END""", reverse_sql=None),
        migrations.RunSQL(sql="""CREATE TRIGGER invoice_line_no_delete BEFORE DELETE ON invoices_invoicelineitem FOR EACH ROW BEGIN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invoice lines cannot be deleted.'; END""", reverse_sql=None),
    ]
